# Generated by Django 4.2.2 on 2023-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name': 'Diagnostico', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostic',
            field=models.CharField(max_length=50, unique=True, verbose_name='Diagnóstico CUD'),
        ),
    ]
