# Generated by Django 4.1.7 on 2023-07-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Alquiler')),
                ('presents', models.BooleanField(default=False, verbose_name='Presente?')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato', verbose_name='Contrato')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
    ]
