# Generated by Django 4.1.7 on 2023-07-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('corp_name', models.CharField(max_length=50, verbose_name='Razón social')),
                ('CUIT', models.CharField(max_length=50, verbose_name='CUIT')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('iva_condition', models.CharField(choices=[(1, 'IVA Responsable Inscripto'), (2, 'IVA Responsable no Inscripto'), (3, 'IVA no Responsable'), (4, 'IVA Sujeto Exento'), (5, 'Consumidor Final'), (6, 'Responsable Monotributo'), (7, 'Sujeto no Categorizado'), (8, 'Proveedor del Exterior'), (9, 'Cliente del Exterior'), (10, 'IVA Liberado  Ley Nº 19.640'), (11, 'IVA Responsable Inscripto  Agente de Percepción'), (12, 'Pequeño Contribuyente Eventual'), (13, 'Monotributista Social'), (14, 'Pequeño Contribuyente Eventual Social')], default=1, max_length=50)),
                ('web_page', models.UUIDField(verbose_name='Pagina web')),
            ],
            options={
                'verbose_name': 'Obra_social',
                'verbose_name_plural': 'Obra_sociales',
            },
        ),
        migrations.CreateModel(
            name='tel_os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=50, verbose_name='Tipo de mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_social.obra', verbose_name='Obra social')),
            ],
        ),
        migrations.CreateModel(
            name='mail_os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(max_length=50, verbose_name='Tipo de mail')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_social.obra', verbose_name='Obra social')),
            ],
        ),
        migrations.CreateModel(
            name='intruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrction', models.TextField(max_length=2500, verbose_name='Instructivo')),
                ('type', models.CharField(max_length=150, verbose_name='Tipo de instructivo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_social.obra', verbose_name='Obra social')),
            ],
        ),
    ]
