# Generated by Django 4.1.7 on 2023-07-02 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(max_length=50, verbose_name='Diagnóstico CUD')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Alta')),
                ('end_date', models.DateField(verbose_name='Baja')),
                ('notes', models.TextField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PROCESING', 'Procesando'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('CANCEL', 'Cancelado'), ('ENDED', 'Finalizado')], default='PROCESING', max_length=50)),
                ('report1', models.DateField(verbose_name='Fecha primer informe semestral')),
                ('report2', models.DateField(verbose_name='Fecha segundo informe semestral')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico', verbose_name='Diagnóstico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContratoPaciente', to='paciente.paciente', verbose_name='Paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContratoProfesional', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
