# Generated by Django 4.1.7 on 2023-07-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PacienteContrato', to='contrato.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Comm_patient',
                'verbose_name_plural': 'Comm_patients',
            },
        ),
        migrations.CreateModel(
            name='Comm_obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, max_length=250, null=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ObraContrato', to='contrato.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Comm_obra',
                'verbose_name_plural': 'Comm_obras',
            },
        ),
    ]
