# Generated by Django 4.1.7 on 2023-07-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_date', models.DateField(verbose_name='Fecha real')),
                ('real_time', models.TimeField(verbose_name='Hora real')),
                ('obra_date', models.DateField(verbose_name='Fecha obra social')),
                ('obra_time', models.TimeField(verbose_name='Hora obra social')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
