# Generated by Django 4.2.2 on 2023-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='mail2',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email2'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel2'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone1',
            field=models.CharField(default=0, max_length=50, verbose_name='Tel1'),
            preserve_default=False,
        ),
    ]
