# Generated by Django 4.1.7 on 2023-07-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_number', models.CharField(max_length=50, verbose_name='Número')),
                ('f_date', models.DateField(verbose_name='Fecha')),
                ('f_months', models.CharField(max_length=450, verbose_name='Meses facturados')),
                ('f_sessions', models.PositiveIntegerField(verbose_name='Sesiones facturadas')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('f_sent', models.DateField(verbose_name='Fecha presentación')),
                ('f_receive', models.DateField(verbose_name='Fecha cobrado')),
                ('status', models.CharField(choices=[('PAYED', 'Pagada'), ('PENDING', 'Pendiente'), ('PARCIAL', 'Parcial'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=50)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
